"$schema" = "https://starship.rs/config-schema.json"

format = """
[](fg:bg0)\
$os\
$username\
[](fg:bg0 bg:blue)\
$directory\
[](fg:blue bg:cyan)\
$git_branch\
$git_status\
[](fg:cyan bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:magenta)\
$docker_context\
[](fg:magenta bg:comment)\
$time\
[ ](fg:comment)\
$line_break$character"""

palette = "tokyo_night"

[palettes.tokyo_night]
bg0 = "#1a1b26"
bg1 = "#24283b"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
orange = "#ff9e64"
red = "#f7768e"
yellow = "#e0af68"
comment = "#565f89"
fg = "#c0caf5"

[os]
disabled = false
style = "bg:bg0 fg:fg"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[username]
show_always = true
style_user = "bg:bg0 fg:fg"
style_root = "bg:bg0 fg:red"
format = "[ $user ]($style)"

[directory]
style = "bg:blue fg:bg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"
read_only_style = "bg:blue fg:bg0"

[git_branch]
symbol = ""
style = "bg:cyan"
format = "[[ $symbol $branch ](bg:cyan fg:bg0)]($style)"

[git_status]
style = "bg:cyan"
format = "[[($all_status$ahead_behind )](bg:cyan fg:bg0)]($style)"

[nodejs]
symbol = ""
style = "bg:green"
format = "[[ $symbol( $version) ](bg:green fg:bg0)]($style)"

[c]
symbol = " "
style = "bg:green"
format = "[[ $symbol( $version) ](bg:green fg:bg0)]($style)"

[rust]
symbol = "󱘗"
style = "bg:green"
format = "[[ $symbol( $version) ](bg:green fg:bg0)]($style)"

[golang]
symbol = ""
style = "bg:green"
format = "[[ $symbol( $version) ](bg:green fg:bg0)]($style)"

[php]
symbol = ""
style = "bg:green"
format = "[[ $symbol( $version) ](bg:green fg:bg0)]($style)"

[java]
symbol = " "
style = "bg:green"
format = "[[ $symbol( $version) ](bg:green fg:bg0)]($style)"

[kotlin]
symbol = ""
style = "bg:green"
format = "[[ $symbol( $version) ](bg:green fg:bg0)]($style)"

[haskell]
symbol = " "
style = "bg:green"
format = "[[ $symbol( $version) ](bg:green fg:bg0)]($style)"

[python]
symbol = " "
style = "bg:green"
format = "[[ $symbol( $version) ](bg:green fg:bg0)]($style)"

[docker_context]
symbol = ""
style = "bg:magenta"
format = "[[ $symbol( $context) ](bg:magenta fg:bg0)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:comment"
format = "[[  $time ](bg:comment fg:fg)]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[](bold fg:green)"
error_symbol = "[](bold fg:red)"
vimcmd_symbol = "[](bold fg:green)"
vimcmd_replace_one_symbol = "[](bold fg:magenta)"
vimcmd_replace_symbol = "[](bold fg:magenta)"
vimcmd_visual_symbol = "[](bold fg:blue)"

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[git_commit]
tag_symbol = "  "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[scala]
symbol = " "

[status]
symbol = " "

[swift]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "
