# =============================================================================
# STARSHIP PROMPT CONFIGURATION - NORD THEME
# =============================================================================
# This configuration file customizes the Starship prompt (https://starship.rs)
# with the Nord color scheme (https://www.nordtheme.com/).

# Schema reference for editor autocompletion and validation
"$schema" = 'https://starship.rs/config-schema.json'

# -----------------------------------------------------------------------------
# Main Prompt Format
# -----------------------------------------------------------------------------
# This defines the overall structure and appearance of the prompt.
# The format uses:
# - Powerline-style transitions between segments with [] characters
# - Various modules that display system and development information
# - Color-coded sections based on the Nord color palette
format = """
[](nord0)\
$os\
$username\
[](bg:nord9 fg:nord0)\
$directory\
[](fg:nord9 bg:nord14)\
$git_branch\
$git_status\
[](fg:nord14 bg:nord7)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:nord7 bg:nord10)\
$docker_context\
[](fg:nord10 bg:nord15)\
$time\
[ ](fg:nord15)\
$line_break$character"""

# -----------------------------------------------------------------------------
# Color Palette - Nord Theme
# -----------------------------------------------------------------------------
# The Nord color scheme is an arctic, bluish color palette
# https://www.nordtheme.com/docs/colors-and-palettes
palette = 'nord'

[palettes.nord]
# Polar Night (dark blues)
nord0 = "#2E3440"  # Dark background
nord1 = "#3B4252"  # Lighter background
nord2 = "#434C5E"  # Selection background
nord3 = "#4C566A"  # Comments, invisibles

# Snow Storm (light whites)
nord4 = "#D8DEE9"  # Main text color
nord5 = "#E5E9F0"  # Lighter text
nord6 = "#ECEFF4"  # Lightest text

# Frost (blues and teals)
nord7 = "#8FBCBB"  # Teal
nord8 = "#88C0D0"  # Light blue
nord9 = "#81A1C1"  # Medium blue
nord10 = "#5E81AC" # Dark blue

# Aurora (colorful accents)
nord11 = "#BF616A" # Red
nord12 = "#D08770" # Orange
nord13 = "#EBCB8B" # Yellow
nord14 = "#A3BE8C" # Green
nord15 = "#B48EAD" # Purple

# -----------------------------------------------------------------------------
# OS Symbols
# -----------------------------------------------------------------------------
# Icons representing different operating systems
[os.symbols]
Windows = "󰍲"     # Windows icon
Ubuntu = "󰕈"      # Ubuntu icon
SUSE = ""        # SUSE icon
Raspbian = "󰐿"   # Raspberry Pi icon
Mint = "󰣭"       # Linux Mint icon
Macos = ""       # macOS icon
Manjaro = ""     # Manjaro icon
Linux = "󰌽"      # Generic Linux icon
Gentoo = "󰣨"     # Gentoo icon
Fedora = "󰣛"     # Fedora icon
Alpine = ""      # Alpine Linux icon
Amazon = ""      # Amazon Linux icon
Android = ""     # Android icon
Arch = "󰣇"       # Arch Linux icon
Artix = "󰣇"      # Artix Linux icon
CentOS = ""      # CentOS icon
Debian = "󰣚"     # Debian icon
Redhat = "󱄛"     # Red Hat icon
RedHatEnterprise = "󱄛" # RHEL icon

# -----------------------------------------------------------------------------
# Module Configurations
# -----------------------------------------------------------------------------

# OS Module - Shows the current operating system
[os]
disabled = false  # Enable the OS module
style = "bg:nord0 fg:nord4"  # Style for the OS icon

# Username Module - Shows the current user
[username]
show_always = true  # Always show username, not just in SSH sessions
style_user = "bg:nord0 fg:nord4"  # Style for regular users
style_root = "bg:nord0 fg:nord11"  # Style for root user (red)
format = '[ $user ]($style)'  # Format with brackets around username

# Directory Module - Shows the current directory
[directory]
style = "fg:nord0 bg:nord9"  # Style with blue background
format = "[ $path ]($style)"  # Format with brackets around path
truncation_length = 3  # Show only 3 parent directories
truncation_symbol = "…/"  # Symbol for truncated directories

# Directory Substitutions - Replace common directories with icons
[directory.substitutions]
"Documents" = "󰈙 "  # Documents folder icon
"Downloads" = " "   # Downloads folder icon
"Music" = "󰝚 "      # Music folder icon
"Pictures" = " "    # Pictures folder icon
"Developer" = "󰲋 "  # Developer folder icon
"code" = "󰲋 "       # Code folder icon

# Git Branch Module - Shows the current git branch
[git_branch]
symbol = ""  # Git branch symbol
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol $branch ](fg:nord0 bg:nord14)]($style)'  # Format with branch name

# Git Status Module - Shows git repository status
[git_status]
style = "bg:nord7"  # Style with teal background
format = '[[($all_status$ahead_behind )](fg:nord0 bg:nord14)]($style)'  # Format with status indicators

# Programming Language Modules - Show version information for various languages
# Each module follows a similar pattern with a unique icon and consistent styling

[nodejs]
symbol = ""  # Node.js icon
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol( $version) ](fg:nord0 bg:nord7)]($style)'  # Format with version

[c]
symbol = " "  # C language icon
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol( $version) ](fg:nord0 bg:nord7)]($style)'  # Format with version

[rust]
symbol = ""  # Rust language icon
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol( $version) ](fg:nord0 bg:nord7)]($style)'  # Format with version

[golang]
symbol = ""  # Go language icon
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol( $version) ](fg:nord0 bg:nord7)]($style)'  # Format with version

[php]
symbol = ""  # PHP language icon
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol( $version) ](fg:nord0 bg:nord7)]($style)'  # Format with version

[java]
symbol = " "  # Java language icon
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol( $version) ](fg:nord0 bg:nord7)]($style)'  # Format with version

[kotlin]
symbol = ""  # Kotlin language icon
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol( $version) ](fg:nord0 bg:nord7)]($style)'  # Format with version

[haskell]
symbol = ""  # Haskell language icon
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol( $version) ](fg:nord0 bg:nord7)]($style)'  # Format with version

[python]
symbol = ""  # Python language icon
style = "bg:nord7"  # Style with teal background
format = '[[ $symbol( $version) ](fg:nord0 bg:nord7)]($style)'  # Format with version

# Docker Context Module - Shows the current Docker context
[docker_context]
symbol = ""  # Docker icon
style = "bg:nord1"  # Style with dark background
format = '[[ $symbol( $context) ](fg:nord8 bg:nord10)]($style)'  # Format with context name

# Time Module - Shows the current time
[time]
disabled = false  # Enable the time module
time_format = "%R"  # 24-hour format (HH:MM)
style = "bg:nord9"  # Style with blue background
format = '[[  $time ](fg:nord0 bg:nord15)]($style)'  # Format with clock icon

# Line Break Module - Adds a line break in the prompt
[line_break]
disabled = false  # Enable line break

# Character Module - Shows the prompt character
[character]
disabled = false  # Enable the character module
success_symbol = '[](bold fg:nord14)'  # Symbol for successful commands (green)
error_symbol = '[](bold fg:nord11)'  # Symbol for failed commands (red)
vimcmd_symbol = '[](bold fg:nord14)'  # Symbol for vim normal mode
vimcmd_replace_one_symbol = '[](bold fg:nord15)'  # Symbol for vim replace one mode
vimcmd_replace_symbol = '[](bold fg:nord15)'  # Symbol for vim replace mode
vimcmd_visual_symbol = '[](bold fg:nord13)'  # Symbol for vim visual mode

# -----------------------------------------------------------------------------
# Performance Optimization
# -----------------------------------------------------------------------------
# For better performance, disable modules you don't use by adding:
# disabled = true
# to their configuration section.
# 
# The Nord theme is designed to be lightweight and efficient.
# Language modules only appear when in a directory with that language detected.