# =============================================================================
# STARSHIP PROMPT CONFIGURATION
# =============================================================================
# This configuration file customizes the Starship prompt (https://starship.rs)
# with a modern, informative, and visually appealing design.

# Schema reference for editor autocompletion and validation
"$schema" = 'https://starship.rs/config-schema.json'

# -----------------------------------------------------------------------------
# Main Prompt Format
# -----------------------------------------------------------------------------
# This defines the overall structure and appearance of the prompt.
# The format uses:
# - Powerline-style transitions between segments with [] characters
# - Various modules that display system and development information
# - Color-coded sections for better visual separation
format = """
[](surface0)\
$os\
$username\
[](bg:peach fg:surface0)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:blue)\
$docker_context\
[](fg:blue bg:purple)\
$time\
[ ](fg:purple)\
$line_break$character"""

# -----------------------------------------------------------------------------
# Color Palette
# -----------------------------------------------------------------------------
# The color scheme used for the prompt
# Options: 'catppuccin_mocha' (default) or 'gruvbox_dark' (alternative)
palette = 'catppuccin_mocha'

# -----------------------------------------------------------------------------
# OS Symbols
# -----------------------------------------------------------------------------
# Icons representing different operating systems
[os.symbols]
Windows = "󰍲"     # Windows icon
Ubuntu = "󰕈"      # Ubuntu icon
SUSE = ""        # SUSE icon
Raspbian = "󰐿"   # Raspberry Pi icon
Mint = "󰣭"       # Linux Mint icon
Macos = ""       # macOS icon
Manjaro = ""     # Manjaro icon
Linux = "󰌽"      # Generic Linux icon
Gentoo = "󰣨"     # Gentoo icon
Fedora = "󰣛"     # Fedora icon
Alpine = ""      # Alpine Linux icon
Amazon = ""      # Amazon Linux icon
Android = ""     # Android icon
Arch = "󰣇"       # Arch Linux icon
Artix = "󰣇"      # Artix Linux icon
CentOS = ""      # CentOS icon
Debian = "󰣚"     # Debian icon
Redhat = "󱄛"     # Red Hat icon
RedHatEnterprise = "󱄛" # RHEL icon

# -----------------------------------------------------------------------------
# Color Palettes
# -----------------------------------------------------------------------------
# Gruvbox Dark Theme
[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'  # Light foreground
color_bg1 = '#3c3836'  # Dark background
color_bg3 = '#665c54'  # Medium background
color_blue = '#458588'  # Blue
color_aqua = '#689d6a'  # Aqua/Teal
color_green = '#98971a'  # Green
color_orange = '#d65d0e'  # Orange
color_purple = '#b16286'  # Purple
color_red = '#cc241d'  # Red
color_yellow = '#d79921'  # Yellow

# Catppuccin Mocha Theme
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"  # Light pink/beige
flamingo = "#f2cdcd"   # Light pink
pink = "#f5c2e7"       # Pink
orange = "#cba6f7"     # Purple-ish
red = "#f38ba8"        # Red
maroon = "#eba0ac"     # Dark pink
peach = "#fab387"      # Peach/Orange
yellow = "#f9e2af"     # Yellow
green = "#a6e3a1"      # Green
teal = "#94e2d5"       # Teal
sky = "#89dceb"        # Light blue
sapphire = "#74c7ec"   # Medium blue
blue = "#89b4fa"       # Blue
lavender = "#b4befe"   # Light purple
text = "#cdd6f4"       # Light text
subtext1 = "#bac2de"   # Slightly darker text
subtext0 = "#a6adc8"   # Even darker text
overlay2 = "#9399b2"   # Overlay color
overlay1 = "#7f849c"   # Darker overlay
overlay0 = "#6c7086"   # Even darker overlay
surface2 = "#585b70"   # Light surface
surface1 = "#45475a"   # Medium surface
surface0 = "#313244"   # Dark surface
base = "#1e1e2e"       # Base background
mantle = "#181825"     # Darker background
crust = "#11111b"      # Darkest background

# -----------------------------------------------------------------------------
# Module Configurations
# -----------------------------------------------------------------------------

# OS Module - Shows the current operating system
[os]
disabled = false  # Enable the OS module
style = "bg:surface0 fg:text"  # Style for the OS icon

# Username Module - Shows the current user
[username]
show_always = true  # Always show username, not just in SSH sessions
style_user = "bg:surface0 fg:text"  # Style for regular users
style_root = "bg:surface0 fg:text"  # Style for root user
format = '[ $user ]($style)'  # Format with brackets around username

# Directory Module - Shows the current directory
[directory]
style = "fg:mantle bg:peach"  # Style with peach background
format = "[ $path ]($style)"  # Format with brackets around path
truncation_length = 3  # Show only 3 parent directories
truncation_symbol = "…/"  # Symbol for truncated directories

# Directory Substitutions - Replace common directories with icons
[directory.substitutions]
"Documents" = "󰈙 "  # Documents folder icon
"Downloads" = " "   # Downloads folder icon
"Music" = "󰝚 "      # Music folder icon
"Pictures" = " "    # Pictures folder icon
"Developer" = "󰲋 "  # Developer folder icon
"code" = "󰲋 "       # Code folder icon

# Git Branch Module - Shows the current git branch
[git_branch]
symbol = ""  # Git branch symbol
style = "bg:teal"  # Style with teal background
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'  # Format with branch name

# Git Status Module - Shows git repository status
[git_status]
style = "bg:teal"  # Style with teal background
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'  # Format with status indicators

# Programming Language Modules - Show version information for various languages
# Each module follows a similar pattern with a unique icon and consistent styling

[nodejs]
symbol = ""  # Node.js icon
style = "bg:teal"  # Style with teal background
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'  # Format with version

[c]
symbol = " "  # C language icon
style = "bg:teal"  # Style with teal background
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'  # Format with version

[rust]
symbol = ""  # Rust language icon
style = "bg:teal"  # Style with teal background
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'  # Format with version

[golang]
symbol = ""  # Go language icon
style = "bg:teal"  # Style with teal background
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'  # Format with version

[php]
symbol = ""  # PHP language icon
style = "bg:teal"  # Style with teal background
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'  # Format with version

[java]
symbol = " "  # Java language icon
style = "bg:teal"  # Style with teal background
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'  # Format with version

[kotlin]
symbol = ""  # Kotlin language icon
style = "bg:teal"  # Style with teal background
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'  # Format with version

[haskell]
symbol = ""  # Haskell language icon
style = "bg:teal"  # Style with teal background
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'  # Format with version

[python]
symbol = ""  # Python language icon
style = "bg:teal"  # Style with teal background
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'  # Format with version

# Docker Context Module - Shows the current Docker context
[docker_context]
symbol = ""  # Docker icon
style = "bg:mantle"  # Style with mantle background
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'  # Format with context name

# Time Module - Shows the current time
[time]
disabled = false  # Enable the time module
time_format = "%R"  # 24-hour format (HH:MM)
style = "bg:peach"  # Style with peach background
format = '[[  $time ](fg:mantle bg:purple)]($style)'  # Format with clock icon

# Line Break Module - Adds a line break in the prompt
[line_break]
disabled = false  # Enable line break

# Character Module - Shows the prompt character
[character]
disabled = false  # Enable the character module
success_symbol = '[](bold fg:green)'  # Symbol for successful commands
error_symbol = '[](bold fg:red)'  # Symbol for failed commands
vimcmd_symbol = '[](bold fg:creen)'  # Symbol for vim normal mode
vimcmd_replace_one_symbol = '[](bold fg:purple)'  # Symbol for vim replace one mode
vimcmd_replace_symbol = '[](bold fg:purple)'  # Symbol for vim replace mode
vimcmd_visual_symbol = '[](bold fg:lavender)'  # Symbol for vim visual mode

# -----------------------------------------------------------------------------
# Performance Optimization
# -----------------------------------------------------------------------------
# To improve performance, you can disable modules you don't use by adding:
# disabled = true
# to their configuration section.
# 
# For example, if you don't use Rust:
# [rust]
# disabled = true